### PR TITLE
Progress2 with global bar support

### PR DESCRIPTION
**Pull request by Agneese-Saini**

### CODE REVIEW

**Comment by Crayder** [comment]
You took out a lot of stuff... Look at the changes...

**Comment by Agneese-Saini** [comment]
Yes i actually remade it with few changes. Like instead of everytime recreating the whole progress-bar in changing color and so, i just set color itself and reshow the TDs. Plus added custom "bgcolor" option. And few things more.

But it doesn't change compatibility at all, actually this is compatible with old progress bar syntax as well.

**Comment by Crayder** [comment]
No I mean from the include, you took the header and a lot of other stuff... xD

You should put it back.

**Comment by Southclaws** [comment]
It would be best if you implemented just the global bars in a separate library since they are predominantly, functionally separate.

I'll probably merge this manually, I'd rather not touch what already works.

**Comment by Agneese-Saini** [comment]
Yea you can merge them, its easy as global bar code is done after playerbar's code (internal functions are done the same way on top) plus you can use your own name convention and so.

I just made this cause i needed global bars with alignment feature.

**Pull request closed without merging**
